[package]
name = "snake_game"
version = "0.1.0"
authors = ["bradybellini <bbellini@pm.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.66.0"
piston2d-opengl_graphics = "0.73.0"